server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///mp?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false
    charset: utf-8
    prefer-file-system-access: false
logging:
  level:
    root: debug
    com.xr.springboot.mapper: trace
  pattern:
    console: '%p%m%n'

